export const soccerChartStatsType = [
    { value: 'Win', label: `Wins` },
    { value: 'Lose', label: `Loses` },
    { value: 'Shot Maps', label: `Shot Maps`, byGames: true },
    { value: 'WinRate', label: `Win Rate` },
    { value: 'GamesPlayed', label: `Games Played` },
    { value: 'GoalsAverage', label: `Goals Average`, byGames: true },
    { value: 'FoulsAverage', label: `Fouls Average`, byGames: true },
    { value: 'MissShotsAverage', label: `MissShots Average`, byGames: true },
    { value: 'TurnOversAverage', label: `TurnOvers Average`, byGames: true },
    { value: 'StealsAverage', label: `Steals Average`, byGames: true },
    { value: 'SavesAverage', label: `Saves Average`, byGames: true },
    { value: 'AssistsAverage', label: `Assists Average`, byGames: true },
    { value: 'CornersAverage', label: `Corners Average`, byGames: true },
    { value: 'AccuracyAverage', label: `Accuracy Average`, byGames: true },
    { value: 'GoalsFor', label: `Goals For`, byGames: true },
    { value: 'GoalsAgainst', label: `Goals Against`, byGames: true },
    { value: 'OverallGoalDifferential', label: `Overall Goal Differential`, byGames: true },
    { value: 'LeaguesPlayed', label: `Leagues Played` },
    { value: 'TournamentsPlayed', label: `Tournaments Played` },
];
