export const basketballChartStatsType = [
    { value: 'Win', label: `Wins` },
    { value: 'Lose', label: `Loses` },
    { value: 'Shot Maps', label: `Shot Maps`, byGames: true },
    { value: 'WinRate', label: `Win Rate` },
    { value: 'GamesPlayed', label: `Games Played` },
    { value: 'PointsAverage', label: `Points Average`, byGames: true },
    { value: 'ShotsTakenAverage', label: `Shots Taken Average`, byGames: true },
    { value: 'AccuracyAverage', label: `Accuracy Average`, byGames: true },
    { value: 'Pts2Average', label: `Pts2 Average`, byGames: true },
    { value: 'Pts3Average', label: `Pts3 Average`, byGames: true },
    { value: 'PenaltyShotsMadeAverage', label: `Penalty Shots Made Average`, byGames: true },
    { value: 'PenaltyShotsAccuracyAverage', label: `Penalty Shots Accuracy Average`, byGames: true },
    { value: 'MissShotsAverage', label: `MissShots Average`, byGames: true },
    { value: 'ReboundsAverage', label: `Rebounds Average`, byGames: true },
    { value: 'StealsAverage', label: `Steals Average`, byGames: true },
    { value: 'BlocksAverage', label: `Blocks Average`, byGames: true },
    { value: 'AssistsAverage', label: `Assists Average`, byGames: true },
    { value: 'FoulsAverage', label: `Fouls Average`, byGames: true },
    { value: 'PointsFor', label: `Points For`, byGames: true },
    { value: 'PointsAgainst', label: `Points Against`, byGames: true },
    { value: 'OverallPointDifferential', label: `Overall Point Differential`, byGames: true },
    { value: 'LeaguesPlayed', label: `Leagues Played` },
    { value: 'TournamentsPlayed', label: `Tournaments Played` },
];
